title: Eolas
description: Curated news about Artificial Intelligence for 2025
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate

# Feed Settings
feed:
  path: feed.xml
  limit: 20
  description: "Latest AI news and updates from Eolas"
  author: "Eolas"
  excerpt: true
  excerpt_separator: <!--more-->

paginate: 5
paginate_path: "/page/:num/"

# SEO Settings
url: "https://joylarkin.github.io"
baseurl: "/CleverAINews"

# Social Media
twitter:
  username: joy # Replace with your Twitter handle
  card: summary_large_image

# Site Author
author: Eolas

# Default SEO Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Eolas AI"
      image: "/assets/images/default-social.jpg" # You'll need to create this image
      share: true

# Google Analytics
google_analytics: [Your Google Analytics tracking ID]

# Additional SEO Settings
lang: en-US
locale: en_US

# Permalink structure
permalink: /:categories/:year/:month/:day/:title.html

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title.html

 
